name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Change this to your Node.js version
        cache: 'npm'

    - name: Install dependencies
      run: npm install


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure this job runs after build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Install dependencies
      run: npm install

    - name: Debug SSH Setup
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa

    - name: Deploy to Remote PC
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PROJECT_DIR: 'E:/proxybackend/proxybackend'
      run: |
        echo -e "Host $REMOTE_HOST\n\tUser $REMOTE_USER\n\tIdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
        chmod 600 ~/.ssh/config
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
        ssh $REMOTE_HOST << 'EOF'
        cd $PROJECT_DIR
        git pull origin main
        npm install
        npm run prisma-push
        npm run sentry:sourcemaps
        pm2 restart all
        EOF