name: Deploy to Windows Remote PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to Windows PC
        shell: bash
        run: |
          for i in {1..5}; do
            ssh -o StrictHostKeyChecking=no Eissanoor@192.168.43.114 << EOF
cd /mnt/e/proxybackend/proxybackend
git pull origin main
npm install
npm start
EOF
            if [ $? -eq 0 ]; then
              echo "Deployment successful!"
              break
            fi
            echo "Retrying SSH connection in 10 seconds..."
            sleep 10
          done
